services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ..:/app
    depends_on:
      - db
    env_file:
      - ../.env
    tty: true
    command: /bin/bash

  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - ../.env

  elasticsearch:
    image: elasticsearch:8.13.4
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  db-data:
    driver: local
  elasticsearch-data:
    driver: local
