services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ..:/app
    depends_on:
      - db
    env_file:
      - ../.env
    tty: true
    command: /bin/bash

  celery_beat:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
      - celerybeat-schedule:/var/celerybeat
    depends_on:
      - redis
    env_file:
      - ../.env
    command: celery --app=drftutorial beat --loglevel=info --schedule /var/celerybeat/schedule.db

  celery_worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - redis
    env_file:
      - ../.env
    command: celery --app=drftutorial worker --loglevel=info

  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - ../.env

  elasticsearch:
    image: elasticsearch:8.13.4
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  redis:
    image: redis:7.2

volumes:
  db-data:
    driver: local
  elasticsearch-data:
    driver: local
  celerybeat-schedule:
    driver: local
