# Generated by Django 5.0.4 on 2024-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
