# Generated by Django 5.0.4 on 2024-05-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_expired_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippet',
        ),
    ]
